spring.datasource.url=jdbc:postgresql://dpg-d89netbtqb8s73fvtdcg-a.oregon-postgres.render.com:5432/gamefinder_db_ofij
spring.datasource.username=gamefinder_db_ofij_user
spring.datasource.password=3E0Ie1XYLfBuu10ZSL8XJ0p0JAtl8JsC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true